### ISSUE TITLE
Platformio download

### ISSUE THREAD

**Issue by antonagestam** [sparkfun/SparkFun_LSM9DS1_Arduino_Library#12]
Hi,

I would love to be able to install this library with platformio just like the lbirary for LSM9DS0 http://platformio.org/lib/show/730/SparkFun%20LSM9DS0%20Breakout

Is this doable?

**Comment by trycoon** [comment]
It's is available: SparkFun LSM9DS1 IMU@1.1.0

**Comment by trycoon** [comment]
Maybe you could close this issue now? Now that even 1.2.0 is out.
