### ISSUE TITLE
Temperature sensor read

### ISSUE THREAD

**Issue by tchristle** [sparkfun/SparkFun_LSM9DS1_Arduino_Library#13]
It does not seam like the correct value is being read from the temperature sensor.  The only values i see from it are 256, 512, 768 and 1024.  I am using the following lines to read the temperature.

```
imu.settings.temp.enabled = true;
imu.readTemp();
Serial.print("T: ");
Serial.println(imu.temperature);
```

**Comment by Grahldg** [comment]
The calculation of temperature was incorrect.  I updated it according to the datasheet and tested it against another sensor.  The latest commit reflects these changes.  If you're still having issues please let me know.
