### ISSUE TITLE
Calibration details?

### ISSUE THREAD

**Issue by glucee** [sparkfun/SparkFun_LSM9DS1_Arduino_Library#17]
Can anyone provide a way to calibrate the chip ?

**Comment by Grahldg** [comment]
Thanks for your question.  We have included some methods for calibrating the sensors in our Arduino Library.  You can call these for an instance of the LSM9DS1 class once it's created.  There are two different methods you can call:

`void LSM9DS1::calibrate(bool autoCalc)`
which calibrates the gyro and accelerometer and
`void LSM9DS1::calibrateMag(bool loadIn)`
which calibrates the magnetometer.

The argument for both methods when `true` will store the determined bias from the calibration to be used when a sensor is read.  Below is an example of how these might be used:

```C
LSM9DS1 imu;
void setup(){
    imu.calibrate(false);         //calibrates but does not store bias
    imu.calibrateMag(true);       //calibrates and stores bias
}
```

**Comment by orionparrott** [comment]
When calibration is called, should the device be stable or in motion? Is there a manual or tutorial somewhere? I could use an example of how and when to call these calibrate functions. Thanks!

**Comment by ransa808** [comment]
Any instruction on how to calibrate ?
I cannot get good heading values ...

**Comment by marcwitteveen** [comment]
Did anybody manage to get this to work or found an example how to use this?
