### ISSUE TITLE
FIFO mode enum bug

### ISSUE THREAD

**Issue by sheitbri** [sparkfun/SparkFun_LSM9DS1_Arduino_Library#19]
In LSM9DS_Types.h  line 174,
FIFO_CONT should equal 6.

**Comment by andreadevo** [comment]
Thank you for the suggestion! However, based on Table 84 located on page 56 of the [datasheet](https://cdn.sparkfun.com/assets/learn_tutorials/3/7/3/LSM9DS1_Datasheet.pdf), it appears FIFO_CONT is currently set to the correct value of 5. May I ask where you are seeing that it should equal 6?

**Comment by sheitbri** [comment]
For continous mode:
FIFOMODE2=1
FIFOMODE1=1
FIFOMODE0=0

So 1*(2<sup>2</sup>) + 1*(2<sup>1</sup>) + 0*(1<sup>0</sup> ) = 4+2+0=  6

**Comment by andreadevo** [comment]
Thank you for following up! I misread the table myself. The code should now correctly reflect FIFO_CONT equal to 6.
