### ISSUE TITLE
No need to wait for data after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [sparkfun/SparkFun_LSM9DS1_Arduino_Library#6]
In two places in the source code there is a while-loop with a delay to wait for data after a call to Wire.requestFrom(). That while-loop and that delay is not needed.

When the Wire.requestFrom() functions returns, the I2C transaction has already completely finished and the received data is in the receive buffer in the Wire library.

**Comment by jimblom** [comment]
Good catch! Made some improvements to both i2c read functions in commit 6a48fe7.
