### ISSUE TITLE
printAttitude mixes degrees and radians incorrectly

### ISSUE THREAD

**Issue by scrain777** [sparkfun/SparkFun_LSM9DS1_Arduino_Library#8]
In the example code for I2C (and presumably for SPI, though I didn't look) it incorrectly computes the heading. If my==0, it sets the heading to 180 degrees, then manipulates the heading as if it were in radians instead. To process the following code correctly, it should be set to pi instead.

**Comment by jimblom** [comment]
Good catch! Fixed in commit 8f9d501.
